### ISSUE TITLE
Help - What does the site show?

### ISSUE THREAD

**Issue by TheLimifiedLime** [TrustedMercury/ghprofile.me#1]
So when looking at my profile it says 0 for everything. I want to know what it counts.

**Comment by kevinjosethomas** [comment]
It counts the number of views your profile/repositories get, have you added the counter to your READMEs?

**Comment by TheLimifiedLime** [comment]
Oh that's what it does? I haven't added it because I wasn't sure what the stats showed at first. I'll probably add it

**Comment by kevinjosethomas** [comment]
Yeah, no way to fetch profile views from GitHub API so you need to add an image to your READMEs. You can learn how to setup here - https://docs.ghprofile.me/features/view-counter

I'm going to add some modal prompts that mentions the required image, thanks for reporting the UX issue.

**Comment by TheLimifiedLime** [comment]
Thanks for the help
