### ISSUE TITLE
Someone stole your discord server

### ISSUE THREAD

**Issue by OmgImAlexis** [trustedmercury/ghprofile.me#16]
@trustedmercury 

![image](https://user-images.githubusercontent.com/6525926/140181783-3ff8bbb1-4512-42e7-b9b2-f6f73d182c48.png)
![image](https://user-images.githubusercontent.com/6525926/140181803-64e5ff4a-ff83-4849-b4a4-f9241598f7a2.png)
![image](https://user-images.githubusercontent.com/6525926/140181828-ba4c99e0-2f5b-4893-93a9-d7f68091cb66.png)
![image](https://user-images.githubusercontent.com/6525926/140181851-24bb39e6-f6df-4b4d-8932-8d3120fd0eef.png)

**Comment by OmgImAlexis** [comment]
crispypeach#9004 - 346744478775771138
Ufo#8033 - 416126435682680842

![image](https://user-images.githubusercontent.com/6525926/140182275-9402b6b3-13a4-43b8-9fcb-d171137f2448.png)

**Comment by trustedmercury** [comment]
Got it back, Helter is my alt. (crispypeach is my brother)

Sorry for the inconvenience, I'll hopefully be back on my main soon.
