### ISSUE TITLE
Views haven't been showing for the last 4 days.

### ISSUE THREAD

**Issue by OmgImAlexis** [TrustedMercury/ghprofile.me#2]
<img width="1160" alt="Screen Shot 2021-01-08 at 10 19 49 am" src="https://user-images.githubusercontent.com/6525926/103957654-19d37000-519b-11eb-8bdf-9c0b8d203b0a.png">
<img width="1164" alt="Screen Shot 2021-01-08 at 10 19 39 am" src="https://user-images.githubusercontent.com/6525926/103957656-1b9d3380-519b-11eb-8487-bc47d3e6e82e.png">

**Comment by kevinjosethomas** [comment]
Looking into it, thanks for reporting!

**Comment by kevinjosethomas** [comment]
Seems like a caching issue. Fixed with a simple restart, thanks for reporting it!
