### ISSUE TITLE
Site not working?

### ISSUE THREAD

**Issue by OmgImAlexis** [TrustedMercury/ghprofile.me#3]
I'm seeing this on the console and the page doesn't do anything further.

```js
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'a.state.data.period')
```

<img width="1488" alt="Screen Shot 2021-06-18 at 9 13 56 am" src="https://user-images.githubusercontent.com/6525926/122485218-889fd980-d015-11eb-87bf-341c49f2fef5.png">

**Comment by kevinjosethomas** [comment]
Fixed earlier, sorry about that!
